services:
  db:
    image: postgres:14
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: sea_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kjsuhwkr # local password
      PGDATA: db-data:/var/lib/postgresql/data/